name: Build Quasar SPA

on:
  push:
    branches: [ "master" ]

jobs:
  spa-build-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci

      - run: npm run build

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/spa
          cname: ${{ secrets.PADDY_APP_CNAME }}
